#!/bin/bash

code="$PYCODE"

# create a file that will store the code
temp_file=$(mktemp)

#copy the code to the file that was created
echo "$code" > "$temp_file"

# run the file
python3 "$temp_file"

#remove the temp file created
rm "$temp_file"
